### ISSUE TITLE
Getting Upgrade Required message when trying to open draw.html

### ISSUE THREAD

**Issue by ToxMox** [vreelb/dewdle#2]
Hi I'm really looking forward to trying this and it seems like the way you've designed this is really well thought out. Running Windows 10 x64. Installed Node JS 64 (tried both Current and LTS releases)

renamed sample config to config.js and left defaults

did npm install in the node js console in the directory where it then installed the dependencies. Opened server.js with node js and it says server running. Then when I tried opening http://localhost:12180/draw.html in Chrome all I get is "Upgrade Required". I'm hoping I'm just doing something stupid.

**Comment by vreelb** [comment]
I'm so glad to see someone trying out my project, thanks for your interest!

One of the things I evidently neglected to do was give the server a way to serve http; right now it only handles websocket connections (hence why it's only saying "Upgrade Required"). The remote server I tested it on already had something going on in that department, so I didn't notice. It shouldn't be too hard for me to bring in express.js to handle that moving forward, and I'll prioritize working on that that soon.

In the interim, if you're only planning to work with it locally you can navigate to the local file with "file:///C:/path/to/dewdle/draw.html" (change that to its location, or just drag the page into a new tab). You shouldn't need to specify the port when loading a local file like that. That's how I did my initial development (and another reason I missed this issue).

Let me know if that solves things for now. I apologise about the bare-bones UI (if you can even call it a UI), I was mainly trying to get the externally visible stuff working first.

**Comment by ToxMox** [comment]
Cool! I'll give this a whirl tonight when I get home. Thanks for the quick response!

**Comment by ToxMox** [comment]
Ok I just tested. Have node.exe running server.js with a message of "Server listening on port 12180...."
Opened draw.html in Chrome and now it opens but it says No Connection Trying to connect...

**Comment by vreelb** [comment]
Hm, well the first problem is worked around now at least.

I think it's a side effect of loading it from a local file. You should be able to change the URL in the config to `'ws://localhost:12180/'` and get it working just fine (make sure you reload all of the html pages).

**Comment by ToxMox** [comment]
Neat! That worked! Thanks :) Now I just need to figure out a good way to overlay the draw window on my OBS preview so I can basically draw right on where it'll render. I'm thinking you've perhaps already thought of a way to do this?

**Comment by vreelb** [comment]
Unfortunately that's still an ongoing R&D item. While the OBS Browser plugin has a Chrome Embedded window (that has a transparent background), that isn't easily an option on the user side. I've given some thought into having a low-quality preview encode, popping out frames here and there, or static templates/guides to help with drawings. The first option I'm not sure how I'd do that with OBS, and it'd still require your computer to handle **two** encodes instead of one, and the second option is better than nothing, but still not as good as actually drawing on the picture.
