### ISSUE TITLE
Render page not working

### ISSUE THREAD

**Issue by whytheheckme** [vreelb/dewdle#6]
Hello,

I'm trying out your software for the first time today. I've cloned the repo, installed per the instructions and run it. I can draw on the canvas just fine, and if I open other instances of the draw page, I can see the thing I've drawn. But the render page is always blank - both in the browser and in OBS. I can see in the console that the application see the render pages connect - I'm just not seeing anything.

Any steps to help troubleshoot? Cool project!
Thanks,
Jacob

**Comment by whytheheckme** [comment]
Another piece of data: when I navigate to the draw page from another device, it serves the page, but the draw box says "No Connection, Trying to connect..."

**Comment by vreelb** [comment]
Hi Jacob, have you made the drawing go live on one of the pages with live control? The Control page has this on by default, on the Draw page it is a config setting. Right now the key for that is spacebar, though I've been thinking there should be a UI element for it as well.

As for the other issue it seems like it is unable to establish a websocket connection, though it was able to be served the web page correctly.

**Comment by whytheheckme** [comment]
Got it, thanks! I'm going to tinker with making it live by default, since I intend on using it in a single user mode. I'll start looking into the websocket.... not sure what's up with that.

**Comment by whytheheckme** [comment]
I'm able to access the websocket port through the browser on the second device (it says "Upgrade Required", the same as it does on the primary device) - not sure what else I should try.

**Comment by whytheheckme** [comment]
Ah, I figured it out. I changed the BASE_URL to not localhost, and now I can access it elsewhere.
Thanks!
